### PR TITLE
Auto Update Post Panel Update 

### PR DESCRIPTION
**Pull request by own3mall**
Takes two updates, but eventually it will run automatically if needed.

### CODE REVIEW

**Comment by own3mall** [comment]
Waiting for @DieFeM review.

**Comment by DieFeM** [comment]
I've noticed you disabled warnings on this line: 
@list($ip_id,$ip,$port,$force_mod_id) = $home_ip_ports[0];
so I guess you've seen warnings, and I was wondering why it would return empty values, it worked fine for me, but not for Rocco, it returned empty ip and port in the new jobs. Do you have any idea?

**Comment by rocco27** [comment]
@DieFeM you mean Yan not me. :-)

**Comment by DieFeM** [comment]
@rocco27 I mean ®omano, I don't know why, but I tend to confuse your nicks, sorry :P

**Comment by own3mall** [comment]
I wanted to look into why it was doing that, but I don't have the old scheduled tasks file anymore so I can test it.  See what I can do...

**Comment by DieFeM** [comment]
@own3mall I had only one job in the in the scheduled task file for testing, and it worked, I found out that you can find the old commands in scheduler.log (in the agent folder), or you can see it from the panel at Cron Admin -> Cron Events.
You maybe can recreate the file using them.

**Comment by own3mall** [comment]
Yeah, something is wrong with the update to new API function.

My tasks file looks like this:

```
0 1 * * * wget -qO- "http://{IP}/opengamepanel/ogp_api.php?gamemanager/restart&token=5546a5e3d1ca580607dfc9f978c5426a2036cfa211a7d8dacee2c6cd6b3ff20b&ip=&port=&mod_key="
```

Test server, so no worries about the token.

**Comment by own3mall** [comment]
It seems to be something about the list() function.  It should be avoided anyways...

This works:

```
$ip_id = $home_ip_ports[0]["ip_id"];
						$port = $home_ip_ports[0]["port"];
						$ip = $home_ip_ports[0]["ip"];
						$force_mod_id = $home_ip_ports[0]["force_mod_id"];
```

Maybe PHP 7 related since list works differently?  

http://php.net/manual/en/function.list.php

**Comment by DieFeM** [comment]
I think I know what happened now... list() is expecting something like array('1', '192.168.0.160', '27015', '0') but it gets array('ip_id' => '1', 'ip' => '192.168.0.160', 'port' => '27015', 'force_mod_id' => '0'), so it does not work. What I can't understand is why it worked for me in first place... I guess is what you said, different php versions behave different.

**Comment by own3mall** [comment]
Note:

    Before PHP 7.1.0, list() only worked on numerical arrays and assumes the numerical indices start at 0.

**Comment by own3mall** [comment]
Doesn't work on associative arrays in older versions.  I personally never use the list command in any of the software I write anyways... I just use associative arrays and their keys.

**Comment by DieFeM** [comment]
Yep, so I was right, they behave differently. So problem solved.

**Comment by DieFeM** [comment]
These two are unnecessary, they are not used, it doesn't hurt the function, but if you can remove them on your next commit, otherwise i'll do it if I need to change something else.
$ip_id = $home_ip_ports[0]["ip_id"];
$force_mod_id = $home_ip_ports[0]["force_mod_id"];

**Pull request merged**
